language: node_js
node_js:
- lts/boron
- node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ecqT21ufc8JZe8R9bmSoTCHG80FsE8hGtXLhtUIwbm0+Jw4NjSuUoSPE+fnp2gjMCR5zF75zGplv8INKbXtzC2lQNehkQQc6eIobORtIqlFEfbvByfR3vnsJODg7smcEGLlLkSzpPt990roUcaNBHHjsN97a2JvIz2Yig9MnLx0fG81CXC2BbutgxmEsIvEsAyzNnIzJABvqzOzzDWLilEB3rAQKMk6lE7Z0cqIXKsjjaHUsTrkcKZSV1o0X7xnZLV/9KCAA02s1/fgT4iNg3leq+oADnrhLxPYZ4bq1pGZ0nv4mfFZZ13drTOpPLa7vxiVSB+wLs8qv/1QnmweTYZqsglQDg420aO2OfQEZVpBpcxny326n30GNppl2olIR1WbFs8FkAB5p3ppKZGA+zQaGuYCbvAJvaFASjSAZYa2MtBs3ay3Vxz5ZzdOniD2gyKfBYK01mB7HVc2YHuTo+bHgb7IicNUeKh5Yy/7LcqJ9+IXJYFM/uigTo5DDzKTntIh3DQLxOqbqWZcuQfALPPEVsh4h8LdtKF5sOtdw/2h0+XGh86fl67C3lXpiOyPdCJbyl4KsmXUD34uVwmeKydSTTdZWeA6RPY21JqcWrW79jZB0lr0bGHA/O7sGtDZTHVDy2s9KMi97zGz9iNH/aGOGc6x7nVWO2sih8dve7RQ=
  file:
    - "retext-syntax-mentions.js"
    - "retext-syntax-mentions.min.js"
  on:
    tags: true
