language: node_js
node_js:
- '4.0'
- '9.0'
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EhpqdrqmZL3VU1Wh+Z4kX4PF64TyCzani9KWd6xFCpJg7ontKc1asWnkf/Lhw67bz0sjjrp8+OuiFrtk/UTaO9knttrmkajUUg1+Nhfm7ICDAe+qgA7d0p6fZu6C2W37GirCJqN/HbBslz/YOM9g11zyziPzasJ585gSzLbejcLVj80ET9QXis20FAm+H/IKv0rcnFX/VVM9zX3fW0VeOyU6x6u6mAP8pXQ5tJdNUZE/3fMMJrP5y4LGLvTBH/ogo15VttPRnkJeOgJQyFO7canXB7c5ZPpdrS+w/0buu8XqHssa+C8Zb/aER7pFcRfeIa124lGjKq0f8Bp/ID+qgSsrh5ckfg+croXSzi4G8PmLlLLIgqqr2N7sHKPUUeg7tEpEw2neBUF9vniaDjOkMVEtsE8Z3K89FDOSJx6mRyOduIql8WQvMoCsi4DJZ7EjExRkGCEbLqbWo360uPP3rmoVDwOnF6Sr5qTfTKp5R8KZUxwnoA8lxQ1NQrcm0gce9w+uFGFDz97Ol2fAdxHRcAUZHgA/ZWuS1+YDW0Tv7cBsgYjg94jWkBDD5pqo685fuiSxeoGX/MvPAqqLOovyHX7GiKD9MndOuHghWc9qaeOF+g13hL3SpGuhzgDrOZlE4a7uT6+RwDElT1xK4MdgRlQ+EV+WqAjrWxJ4KmURhHo=
  file:
    - "retext-syntax-mentions.js"
    - "retext-syntax-mentions.min.js"
  on:
    tags: true
